/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matrices.tutorial.type;

import java.awt.GridBagConstraints;
import matrices.main.form.MatrixEdit;
import matrices.math.Matrix;
import javax.swing.JPanel;
import matrices.main.form.MatrixShow;
import matrices.tutorial.type.section.TutorialSection;
import java.awt.Dimension;
import javax.swing.JFrame;
import matrices.Util;
import matrices.tutorial.form.MatrixTutorial2;
import matrices.tutorial.type.TutorialResourceProvider;
import matrices.tutorial.type.button.Button;
import matrices.tutorial.type.section.TutorialSection;
import java.util.ArrayList;
import matrices.tutorial.type.section.TutorialSection;

/**
 *
 * @author MojoMacW7
 */
public class MatrixSection extends JPanel{
    

    /**
     * Creates new form MatrixSection
     */
    MatrixShow matrixShow = null;
    public Matrix matrix = null;
    public MatrixSection(Matrix m) {
        this.matrix = m;
        initComponents();
        setDoubleBuffered(true);
        matrixShow = new MatrixShow();
        matrixShowHolder.add(matrixShow);
    }
    public void addButton(Button button){
        GridBagConstraints constraints = button.getConstraints();
        constraints.gridy = constraints.gridx;
        constraints.gridx = 0;
        bottomPanel.add(button, constraints);
    }
    
    public final void loadMatrix(Matrix m){
        this.matrix = m;
        matrixShow.loadMatrix(m);
    }
    
    public void fitTable(){
        matrixShow.fitTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        matrixShowHolder = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        matrixShowHolder.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(matrixShowHolder, gridBagConstraints);

        bottomPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(bottomPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel matrixShowHolder;
    // End of variables declaration//GEN-END:variables
}
