/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matrices.main.form;

import matrices.main.type.MatrixPanel;
import javax.swing.JTabbedPane;
import javax.swing.JPanel;

/**
 *
 * @author MojoMacW7
 */
public class MainTab extends javax.swing.JPanel {

    /**
     * Creates new form MainTab
     */
    boolean shown = false;
    String title;
    int index;
    JPanel panel;
    JTabbedPane tabbedPane;
    String tooltip;
    public MainTab(JTabbedPane tabbedPane, JPanel panel, String title, String tooltip, int index) {
        initComponents();
        setDoubleBuffered(true);
        this.tabbedPane = tabbedPane;
        this.title = title;
        this.panel = panel;
        this.index = index;
        this.tooltip = tooltip;
        this.add(panel);
    }
    public boolean isShown(){
        return shown;
    }
    public void showTab(boolean show){
        if(show == this.shown){
            return;
        }
        this.shown = show;
        
        if(show){
            tabbedPane.insertTab(title, null, this, tooltip, index);
        }else{
            tabbedPane.remove(this);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
